version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ./backend/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 3000:3000
    command: bash -c "rm -f /tmp/pids/server.pid && bundle exec rails s -p '3000' -b '0.0.0.0'"
    volumes:
      - ./backend:/app_name
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - mysql
    tty: true
    stdin_open: true
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8080:8080
    command: npm run serve
    volumes:
      - ./frontend:/app_name
      - frontend-node_modules:/app_name/node_modules
    depends_on:
      - backend
    tty: true
volumes:
  frontend-node_modules: